# docker compose build <service_name> to rebuild specific servicecompose build db
# to connect to strava db in superset: use host=host.docker.internal, port=5433
services:
  db:
    build: ./database/
    ports:
      - 5433:5432
  app:
    build: ./app/
    volumes:
      - ./app/data/:/data
    depends_on:
      - db