# docker compose build <service_name> to rebuild specific service
# to connect to strava db in superset: use host=host.docker.internal, port=5433
services:
  db:
    build: ./database/
    ports:
      - 5433:5432
  app:
    build: ./app/
    volumes:
      - data:/home/yosyp-cav/dev/strava-analytics/app
    depends_on:
      - db

volumes:
  data: