# docker compose build <service_name> to rebuild specific servicecompose build db
services:
  db:
    build: ./database/
    #hostname: localhost
    ports:
      - 127.0.0.1:5432:5432
  app :
    build: ./app/
    volumes:
      - ./app/data/:/data
    depends_on:
      - db