# docker compose build <service_name> to rebuild specific servicecompose build db
services:
  db:
    build: ./database/
    ports:
      - 5433:5432
  app :
    build: ./app/
    volumes:
      - ./app/data/:/data
    depends_on:
      - db